# 공통 지침 (모든 종목 공유)
# 수정 시 모든 프롬프트에 자동 반영

scoring_guide: |
  ## overall_score (0~100점)
  - 90~100: 프로급 동작
  - 80~89: 우수 (아마추어 상급)
  - 70~79: 양호 (중급)
  - 60~69: 개선 필요 (초급)
  - 60 미만: 많은 교정 필요

feedback_guide: |
  ## feedback (2~3문장, 한글)
  - 구체적인 각도 수치를 반드시 언급
  - "왜" 그런지 간단히 설명
  - 긍정적이고 건설적인 톤 유지
  - 개선 방법을 명확하게 제시

improvements_guide: |
  ## improvements (최대 3개)
  - 이상 범위를 벗어난 항목만 포함
  - 각 항목:
    - issue: 문제점 (전문 용어 사용 OK)
    - current_value: 측정값
    - ideal_range: 이상 범위
    - suggestion: 구체적 개선 방법 (1~2문장)
    - "~~을 현재 XX도에서 YY도로 조정하세요"
    - "~~할 때 ~~에 주의하세요"
    - 구체적 수치 포함 필수

json_rules: |
  **절대 지켜야 할 규칙:**
  1. 오직 JSON 텍스트만 출력하세요.
  2. 마크다운 코드 블록(```json)을 절대 사용하지 마세요.
  3. 설명 문구나 주석을 추가하지 마세요.
  4. JSON 파싱이 반드시 가능해야 합니다.

output_format: |
  출력 형식:
  {
    "overall_score": 85,
    "feedback": "전반적으로 좋은 자세입니다. 강점을 유지하면서 개선점을 보완하세요.",
    "improvements": [
      {
        "issue": "왼팔 각도가 이상 범위보다 약간 낮습니다",
        "current_value": 158.3,
        "ideal_range": [165.0, 180.0],
        "suggestion": "백스윙 시 왼팔 팔꿈치를 더 펴주세요. 거울을 보며 연습하면 효과적입니다."
      }
    ]
  }
